/* Do Not Edit this File
 * - Restrictions on Student Code: Do not post your code on any public site (eg. Github).
 * - Date: Jan 2025
 */

#ifndef SMALLFP_PRECISION_H
#define SMALLFP_PRECISION_H

// Floating Point Precision
#define SMALLFP_SPECIAL      1
#define SMALLFP_SIGNED       1
#define SMALLFP_DENORMALIZED 0
#define SMALLFP_ROUND_EVEN   1
#define SMALLFP_SIGN_BITS    1
#define SMALLFP_EXP_BITS     4 
#define SMALLFP_FRAC_BITS    6
#define SMALLFP_TOTAL_BITS   SMALLFP_SIGN_BITS + SMALLFP_EXP_BITS + SMALLFP_FRAC_BITS

#endif
